/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SanketGpt {
    }
}
declare global {
    interface HTMLSanketGptElement extends Components.SanketGpt, HTMLStencilElement {
    }
    var HTMLSanketGptElement: {
        prototype: HTMLSanketGptElement;
        new (): HTMLSanketGptElement;
    };
    interface HTMLElementTagNameMap {
        "sanket-gpt": HTMLSanketGptElement;
    }
}
declare namespace LocalJSX {
    interface SanketGpt {
    }
    interface IntrinsicElements {
        "sanket-gpt": SanketGpt;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sanket-gpt": LocalJSX.SanketGpt & JSXBase.HTMLAttributes<HTMLSanketGptElement>;
        }
    }
}
